import os
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.runnables import RunnablePassthrough
from .models import QuizOutput 

# --- CRITICAL FIX: Tell dotenv where to find the file ---
from pathlib import Path
dotenv_path = Path('.') / 'backend' / '.env'
load_dotenv(dotenv_path=dotenv_path)
# --------------------------------------------------------

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found. Check your .env file.")

model = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash", 
    api_key=GEMINI_API_KEY,
    temperature=0
)

parser = JsonOutputParser(pydantic_object=QuizOutput)

QUIZ_GENERATION_TEMPLATE = """
You are an expert educational assistant. Your task is to analyze the provided Wikipedia article text and generate a structured, educational quiz.

--- Article Title: {title} ---
--- Article Content: ---
{scraped_content}
--- End of Content ---

INSTRUCTIONS:
1. Generate between 5 and 10 quiz questions based ONLY on the provided content.
2. Each question must have exactly four options (A, B, C, D).
3. Provide the exact correct answer from the options, a short explanation, and a difficulty level ('easy', 'medium', or 'hard').
4. Extract 3-5 relevant and specific 'related_topics' for further reading based on the content.
5. Identify a dictionary of 'key_entities' categorized by 'people', 'organizations', and 'locations'.
6. Infer the main historical or conceptual 'sections' covered in the text (e.g., 'Early Life', 'Impact', 'Technology').
7. The output MUST strictly conform to the following JSON schema. Do not include any text outside the JSON object.

{format_instructions}

Generated Quiz (in JSON format):
"""

prompt = PromptTemplate(
    template=QUIZ_GENERATION_TEMPLATE,
    input_variables=["title", "scraped_content"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)

quiz_generation_chain = (
    RunnablePassthrough.assign(
        format_instructions=lambda x: parser.get_format_instructions()
    )
    | prompt
    | model
    | parser
)

def generate_quiz_data(title: str, url: str, scraped_content: str) -> QuizOutput:
    if not scraped_content.strip():
        # Raise an error if the scraper returns empty content
        raise ValueError("Scraped content is empty. Cannot generate quiz.")
        
    # 1. Invoke the chain. The result is a Python DICT from the JsonOutputParser.
    try:
        result_dict = quiz_generation_chain.invoke({
            "title": title, 
            "scraped_content": scraped_content
        })
    except Exception as e:
        # Catch errors during the LLM call itself (e.g., API key, rate limit)
        print(f"LLM chain invocation failed: {e}")
        raise ValueError(f"LLM quiz generation failed. Details: {e}")
    
    # 2. Add the title and URL fields to the dictionary
    # These fields are required by the QuizOutput model but are not generated by the LLM.
    result_dict["url"] = url
    result_dict["title"] = title
    
    # 3. CRITICAL STEP: Create the Pydantic model instance from the dictionary.
    # This correctly validates the data and creates the object instance.
    try:
        final_quiz_output = QuizOutput(**result_dict)
        return final_quiz_output
    except Exception as e:
        # Catch errors if the LLM output is malformed and fails Pydantic validation
        print(f"Pydantic validation/instantiation failed: {e}")
        raise ValueError(f"LLM output could not be parsed into Quiz model. The LLM provided malformed JSON. Details: {e}")